<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_50</name>
   <tag></tag>
   <elementGuidId>218d65fa-cf87-4be9-a8db-73e019682235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-3 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98c3616e-f6eb-4f3d-abaa-9f20434afbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>2e6b58e6-4c06-49a0-895c-89a8daa4e88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>10fb6f29-cdc6-4b78-94de-1eb14c9fb2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-3&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>654c0880-a2f7-4611-8bc1-328d8a79824c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-3']/span</value>
      <webElementGuid>b4fda42e-95d6-4df8-a2a0-e62459fb6413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encuesta anfitrión'])[1]/following::span[3]</value>
      <webElementGuid>2df95513-1029-4bcb-ab89-50d31ba72cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar reservación'])[1]/following::span[3]</value>
      <webElementGuid>2845d6ec-150c-42fc-8fa1-da50afcb4855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50']/parent::*</value>
      <webElementGuid>a6598410-7045-4946-bf00-d2e8aeacc253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>6ec5d67b-5bbb-4913-9d8d-b3e3e7d074a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '50' or . = '50')]</value>
      <webElementGuid>3ab55540-e024-4fec-aea6-51d13b28e72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
