<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cantos huspedes</name>
   <tag></tag>
   <elementGuidId>51e6a85e-e203-476a-bf77-e12806913e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='huespedes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#huespedes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ec0f7dc-b461-4138-930c-e671cda6725b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a01c702-b059-43fe-8069-35fd4ef7ec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>30871f0d-d9d1-4783-84f7-319997e3bc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>huespedes</value>
      <webElementGuid>19bf4f80-b268-4597-aabc-379aa6717759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d93d10c2-fcc4-4d9f-b88e-8499db86f1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¿Cúantos huéspedes?</value>
      <webElementGuid>7e06443c-a5ae-4092-8cf4-b0d07a3ca926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huespedes&quot;)</value>
      <webElementGuid>8e919ea3-50e4-4c01-8c4e-488d308fad06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='huespedes']</value>
      <webElementGuid>44f2273a-7f06-48f1-ae1b-95f498a4f85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/form/div/div/div[4]/div/a</value>
      <webElementGuid>85fa0458-5c4c-4ea1-8401-af726ee8c998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'¿Cúantos huéspedes?')]</value>
      <webElementGuid>73610d50-6292-4df9-b9fe-7b4c6e4d6734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha final'])[1]/following::a[1]</value>
      <webElementGuid>4e3adde6-3ea1-40fa-85bc-b6854c9a6620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha inicial'])[1]/following::a[1]</value>
      <webElementGuid>497c3c25-9b4a-4a10-a47e-10aea63d9289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adultos'])[1]/preceding::a[1]</value>
      <webElementGuid>57b7f30b-9e03-4797-ae3f-f7dd96cca457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Niños'])[1]/preceding::a[1]</value>
      <webElementGuid>eba4b892-7050-4cf5-92e4-32f1e490ae73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¿Cúantos huéspedes?']/parent::*</value>
      <webElementGuid>b23a92d8-e763-4c50-8acf-4b471560b7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>a8ea13bd-b02e-4fe1-8b25-1c7b47a287f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'huespedes' and (text() = '¿Cúantos huéspedes?' or . = '¿Cúantos huéspedes?')]</value>
      <webElementGuid>2d507d80-14b9-4028-9ff0-f052308dd08e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
