<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ie Soluciones_mat-calendar-arrow mat-ca_138a15</name>
   <tag></tag>
   <elementGuidId>4e74319d-3689-4669-aa91-5904e480c238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-calendar[@id='mat-datepicker-1']/mat-calendar-header/div/div/button/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-calendar-arrow.mat-calendar-invert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6536a9c4-a67d-4b1b-9df1-ad82f0a544b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-calendar-arrow mat-calendar-invert</value>
      <webElementGuid>07869de0-7d41-4b4c-97a9-689a85ab8521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-datepicker-1&quot;)/mat-calendar-header[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-calendar-header&quot;]/div[@class=&quot;mat-calendar-controls&quot;]/button[@class=&quot;mat-calendar-period-button mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/div[@class=&quot;mat-calendar-arrow mat-calendar-invert&quot;]</value>
      <webElementGuid>0337bda8-2000-40bb-848f-a0cd33102aaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-calendar[@id='mat-datepicker-1']/mat-calendar-header/div/div/button/span/div</value>
      <webElementGuid>e99cbf6b-3d08-4235-aebb-dcec63eccf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>4d1962d7-c567-4bb9-a79d-19b634f0c2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
