<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Estatus_mat-select-arrow</name>
   <tag></tag>
   <elementGuidId>7d6cf1dc-1e5a-49d0-8146-78559aa87dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-4']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-4 > div.mat-select-trigger > div.mat-select-arrow-wrapper > div.mat-select-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>094b4beb-d63a-414d-9524-97bf210da3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow</value>
      <webElementGuid>59d17b22-b0ba-435e-b121-5cc4b7b5d5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-4&quot;)/div[@class=&quot;mat-select-trigger&quot;]/div[@class=&quot;mat-select-arrow-wrapper&quot;]/div[@class=&quot;mat-select-arrow&quot;]</value>
      <webElementGuid>33f512c3-da87-493a-a385-eeac575863d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-4']/div/div[2]/div</value>
      <webElementGuid>0672211c-7993-4d82-b459-79e35ad644d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field/div/div/div/mat-select/div/div[2]/div</value>
      <webElementGuid>d1f1cd08-03fa-4356-b2b2-2992c930d5f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
