<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_add</name>
   <tag></tag>
   <elementGuidId>0eb22d8a-d57a-4b72-83f8-9b8513bdea3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/form/div/div/div[4]/div/div/div/div[2]/button[2]/span/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-icon-button.mat-button-base.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.material-icons.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>e91c5270-d406-4535-94f3-d8722e3a15f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>89f77b12-fc4d-4a91-8013-bbefce361163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8c7dfd2c-8e61-4e00-a922-1e09e97260f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e289db3-2ba7-441e-ba39-b5f33118423d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>8329aeb3-3576-4a30-a354-680cb78a5fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;p-3 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;kt-form kt-form--group-seperator-dashed ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;kt-form__section kt-form__section--first&quot;]/div[@class=&quot;right-last-item&quot;]/div[@class=&quot;ml-3&quot;]/div[@class=&quot;d-inline-block show dropdown&quot;]/div[@class=&quot;dropdown-menu-huespedes dropdown-menu m-0 dropdown-menu-right dropdown-menu-anim-up dropdown-menu-lg show&quot;]/div[@class=&quot;dropdown-menu-huespedes__container ng-star-inserted&quot;]/div[@class=&quot;huespedes-container__buttons&quot;]/button[@class=&quot;mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>cba89486-699c-4a3b-94cd-cdf23c23dfd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/form/div/div/div[4]/div/div/div/div[2]/button[2]/span/mat-icon</value>
      <webElementGuid>93fa937e-f4ba-4ab9-aee3-769634cac7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adultos'])[1]/following::mat-icon[2]</value>
      <webElementGuid>bdece834-808b-491d-a559-b07b0d6ef034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cúantos huéspedes?'])[1]/following::mat-icon[2]</value>
      <webElementGuid>fd8cdbc6-528d-4a07-b54d-0b2ffbfb5d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Niños'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>014b72bb-185b-49a2-a291-370ae78b54e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar disponibilidad'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>8ccb02be-919e-447f-8331-5f7a39cc920c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='add']/parent::*</value>
      <webElementGuid>ec3777c8-ce6d-4198-ae9a-e91caa48462f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/mat-icon</value>
      <webElementGuid>ede31b35-9e1f-42de-b7b0-fd3293d90d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>74a362bd-def2-4f03-93d4-e691f62e993f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
