<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Reservaciones</name>
   <tag></tag>
   <elementGuidId>d5e91d7b-2beb-4d1f-8894-a50895aea035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_header_menu']/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.kt-menu__item.kt-menu__item--active.kt-menu__item--here.kt-menu__item--rel.ng-star-inserted.kt-menu__item--hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cd9e3969-1114-4aab-838e-26148c6dda54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-menu__item kt-menu__item--active kt-menu__item--here kt-menu__item--rel ng-star-inserted kt-menu__item--hover</value>
      <webElementGuid>9932716d-5095-4b8c-ba80-545847510d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>259ef148-dd3a-40bf-83f0-1b2a3acc2bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ktmenu-submenu-toggle</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>03cb49db-f88e-44a5-99f0-aa24065b022b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Reservaciones </value>
      <webElementGuid>1b621aea-bd85-4c68-857e-816b6d56353d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header_menu&quot;)/ul[@class=&quot;kt-menu__nav&quot;]/li[@class=&quot;kt-menu__item kt-menu__item--active kt-menu__item--here kt-menu__item--rel ng-star-inserted kt-menu__item--hover&quot;]</value>
      <webElementGuid>3e21b58a-dd17-4b8d-9766-01f46e70a330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_header_menu']/ul/li</value>
      <webElementGuid>e4c128a7-23ac-470d-b49e-c7a93b8f5053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catálogos'])[1]/preceding::li[1]</value>
      <webElementGuid>9a934f59-13ca-49ca-a4dc-22f6f705f648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>906965a4-5ad2-482c-a00c-d78b432ed3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' Reservaciones ' or . = ' Reservaciones ')]</value>
      <webElementGuid>85dd4cc2-e4d4-4769-9977-45a8489f9a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
