<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_50</name>
   <tag></tag>
   <elementGuidId>599b1328-077e-4b3d-b735-bbb4f3276fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-9']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-9 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be75bcc0-06e3-4b8b-b1ac-9ee5a3d9face</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>c204ba74-4f1e-4474-ad48-9f11f49b4423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c9cc7120-cf77-4ff7-ac65-3abee78f76a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-9&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>aaa5becf-fd6d-45e2-bc89-c29deb38e08f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-9']/span</value>
      <webElementGuid>a772103c-effb-4fe7-936f-da99efa57086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-option-9', '&quot;', ')/span[@class=', '&quot;', 'mat-option-text', '&quot;', ']')])[1]/following::span[3]</value>
      <webElementGuid>e85b8a84-748b-4720-aefb-b4fc77688321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ie Soluciones'])[1]/following::span[3]</value>
      <webElementGuid>14b3a03b-00ba-496d-a566-42103444684f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear nueva tarifa'])[1]/preceding::span[2]</value>
      <webElementGuid>1498ee9a-552f-49bb-bb9c-223544b1b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50']/parent::*</value>
      <webElementGuid>c5bc1de2-78e4-4a28-a0ee-380e2c8ccac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>7251a769-9872-48e1-8b82-6321767ba286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '50' or . = '50')]</value>
      <webElementGuid>e1fbf953-33e8-41a2-89c1-2e0e0d5a4251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
